openapi: 3.0.0
info:
  title: "a"
  description: Do things
  contact: {}
  version: 0.0.1
paths:
  /my/resource:
    get: 
      operationId: doThing
      description: Do the thing!
      tags:
      - Things
      responses:
        "204":
          description: An empty success
        "400":
          $ref: 'https://astromechza.github.io/api-first-playground/common-api.yaml#/components/responses/400'
        "401":
          $ref: 'https://astromechza.github.io/api-first-playground/common-api.yaml#/components/responses/401'
